[workspace]
resolver = "2"
members = ["runner", "benches", "examples/starknet"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
cairo-felt = "0.9"
cairo-lang-casm = "2.5.0"
cairo-lang-runner = "2.5.0"
cairo-lang-sierra = "2.5.0"
cairo-lang-utils = "2.5.0"
cairo-proof-parser = { git = "https://github.com/Okm165/cairo-proof-parser" }
cairo-vm = "0.9.2"
clap = { version = "4", features = ["derive"] }
itertools = "0.12.0"
num-bigint = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"