[package]
name = "channel_contract"
version = "0.1.0"

[dependencies]
openzeppelin = { workspace = true }
snforge_std = { workspace = true }
starknet = { workspace = true }
channel = { workspace = true }

[[target.starknet-contract]]
sierra = true
casm = true