name: CI
on:
  push:
  merge_group:
  pull_request:
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - run: scarb test
  
  verify-layout:
    strategy:
      matrix:
        layout: ["dex", "recursive", "recursive_with_poseidon", "small", "starknet"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: software-mansion/setup-scarb@v1
      - run: python configure.py -l {${{ matrix.layout }}} -s keccak
      - run: scarb build
      - run: cargo run --release --bin runner -- target/dev/cairo_verifier.sierra.json < examples/proofs/{${{ matrix.layout }}}/example_proof.json