name: Continuous Integration - tests

on:
  push:
  pull_request:

jobs:
  formatting-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
      
      - name: Format code
        run: scarb fmt --check
      
      # temporary solution
      - name: Clone custom scarb
        run: |
          git clone https://github.com/fmkra/scarb.git
        working-directory: ${{ github.workspace }}
      
      # temporary solution
      - name: Build custom scarb
        run: cargo build
        working-directory: ${{ github.workspace }}/scarb
      
      - name: Run tests
        run: ./scarb/target/debug/scarb test
        working-directory: ${{ github.workspace }}